title = "Kat Plata"
baseURL = ""
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
relativeURLs = "true"
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = "Hi. Call me Kat"
  author = "Kathryn Plata"
  description = "This is my personal blog."
  logoBig = "/images/turkey.png"
  logoSmall = "/images/turkey.png"
  favicon = "favicon.ico"
  opengraphImage = "/images/turkey.png"
  email = "therealkatplata@gmail.com"
  googleTagManger = ""
  customCSS = false

  # Social media links in footer
  # twitter = ""
  linkedin = "ruhlk"
  github = "Platakg"
  # facebook = ""

  # Copyright and theme author credit in footer
  copyright = true
  credit = true

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = false
  cacheBustJS = false

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = "https://usebasin.com/f/0eae7044d4c2"

[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Gallery"
  url  = "/#work"
  weight = 2
[[menu.main]]
  name = "Blog"
  url  = "/#blog"
  weight = 3
[[menu.main]]
  name = "Contact"
  url  = "/#contact"
  weight = 4
